import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';

const root=process.cwd();const issues=[];const config=JSON.parse(readFileSync(join(root,'site-config.json'),'utf8'));const htmlFiles=readdirSync(root,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()&&e.name.endsWith('.html')&&!e.parentPath.includes('source-images')&&!e.parentPath.includes('.git')).map(e=>join(e.parentPath,e.name));const indexable=[];const titles=new Map(),descs=new Map();
const remember=(map,value,file,label)=>{if(map.has(value))issues.push(`Duplicate ${label}: ${value}`);else map.set(value,file)};
for(const file of htmlFiles){const html=readFileSync(file,'utf8');const name=relative(root,file);const is404=name==='404.html';const title=html.match(/<title>([^<]+)<\/title>/i)?.[1]??'';const desc=html.match(/<meta name="description" content="([^"]+)"/i)?.[1]??'';const robots=html.match(/<meta name="robots" content="([^"]+)"/i)?.[1]??'';const h1=(html.match(/<h1\b/gi)||[]).length;
  if(!/<html lang="ar" dir="rtl">/i.test(html))issues.push(`${name}: missing Arabic RTL declaration`);if(!title)issues.push(`${name}: missing title`);if(!is404&&!desc)issues.push(`${name}: missing description`);if(h1!==1)issues.push(`${name}: expected one H1, found ${h1}`);if(!robots)issues.push(`${name}: missing robots meta`);if(!is404&&!robots.startsWith('index'))issues.push(`${name}: important page is not indexable`);if(!is404){remember(titles,title,file,'title');remember(descs,desc,file,'description');indexable.push(file);if(!html.includes('<link rel="canonical" href="./">'))issues.push(`${name}: missing self-relative canonical`);if(!html.includes('property="og:title"')||!html.includes('name="twitter:card"'))issues.push(`${name}: incomplete social metadata`);if(!html.includes('tel:+966536469949')||!html.includes('https://wa.me/966536469949'))issues.push(`${name}: missing official contact links`)}
  if(/(?:Abu\s*Jassar|Abujassar|أبو\s*جسار|Amjad|أمجد|amjadblacksmith)/i.test(html))issues.push(`${name}: old business reference`);const phones=[...html.matchAll(/(?:\+966|966)\d{9}/g)].map(m=>m[0]);for(const phone of phones)if(!phone.endsWith('536469949'))issues.push(`${name}: unexpected phone ${phone}`);if(/(?:href|src)="\/(?!\/)/.test(html))issues.push(`${name}: root-relative path`);if(/href="[^"]*index\.html/.test(html))issues.push(`${name}: internal index.html link`);
  for(const m of html.matchAll(/(?:href|src)="([^"#?]+)"/g)){const value=m[1];if(/^(?:https?:|tel:|mailto:)/.test(value))continue;const target=resolve(dirname(file),decodeURIComponent(value));if(!existsSync(target))issues.push(`${name}: missing target ${value}`)}
  for(const m of html.matchAll(/<img\b[^>]*>/gi)){const tag=m[0];if(!/alt="[^"]+"/.test(tag))issues.push(`${name}: image missing useful alt`);if(!/width="\d+"/.test(tag)||!/height="\d+"/.test(tag))issues.push(`${name}: image dimensions missing`)}
  for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi)){try{JSON.parse(m[1])}catch(e){issues.push(`${name}: invalid JSON-LD ${e.message}`)}}
}
const publicText=htmlFiles.map(file=>readFileSync(file,'utf8')).join('\n');const retiredPhones=[['050','600','8916'].join(''),['506','008','916'].join(''),['538','341','379'].join('')];for(const oldPhone of retiredPhones)if(publicText.replaceAll(' ','').includes(oldPhone))issues.push(`Old business phone detected: ${oldPhone}`);
const webp=readdirSync(join(root,'assets/images'),{recursive:true,withFileTypes:true}).filter(e=>e.isFile()&&e.name.endsWith('.webp'));if(webp.length!==32)issues.push(`Expected 32 optimized WebP images, found ${webp.length}`);for(const image of webp){const full=join(image.parentPath,image.name);const used=htmlFiles.some(file=>readFileSync(file,'utf8').includes(image.name));if(!used)issues.push(`Unused image: ${relative(root,full)}`)}
if(config.origin){const map=readFileSync(join(root,'sitemap.xml'),'utf8');const urls=(map.match(/<loc>/g)||[]).length;if(urls!==indexable.length)issues.push(`Sitemap has ${urls} URLs for ${indexable.length} pages`);if(!readFileSync(join(root,'robots.txt'),'utf8').includes(`Sitemap: ${config.origin}/sitemap.xml`))issues.push('robots.txt sitemap mismatch')}else console.warn('NOTICE: production domain is not configured; absolute sitemap and canonical URLs must be finalized after the domain is supplied.');
if(issues.length){console.error(`QA failed with ${issues.length} issue(s):\n- ${issues.join('\n- ')}`);process.exit(1)}console.log(`QA passed: ${indexable.length} indexable pages, ${htmlFiles.length} HTML files, ${webp.length} optimized images, valid links, metadata, schema, and official phone only.`);
